// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lizi_mail_api.Infra;

#nullable disable

namespace lizi_mail_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221235454_create_database_lizi_mail")]
    partial class create_database_lizi_mail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("lizi_mail_api.Entities.ApiKeyEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("key_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("api_keys");
                });

            modelBuilder.Entity("lizi_mail_api.Entities.EmailEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("api_key_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("error_message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("provider_message_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("to_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("api_key_id");

                    b.HasIndex("user_id");

                    b.ToTable("emails");
                });

            modelBuilder.Entity("lizi_mail_api.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("plan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("lizi_mail_api.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("lizi_mail_api.Entities.UserEntity", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ApiKey_User");

                    b.Navigation("user");
                });

            modelBuilder.Entity("lizi_mail_api.Entities.EmailEntity", b =>
                {
                    b.HasOne("lizi_mail_api.Entities.ApiKeyEntity", "api_key")
                        .WithMany()
                        .HasForeignKey("api_key_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Email_ApiKey");

                    b.HasOne("lizi_mail_api.Entities.UserEntity", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Email_User");

                    b.Navigation("api_key");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
